$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $root ".env.local"

$keys = @(
  @{ Name = "OPENAI_API_KEY"; Label = "OpenAI API key" },
  @{ Name = "ANTHROPIC_API_KEY"; Label = "Anthropic API key" },
  @{ Name = "ELEVENLABS_API_KEY"; Label = "ElevenLabs API key" },
  @{ Name = "ELEVENLABS_AGENT_ID"; Label = "ElevenLabs Agent ID"; Plain = $true },
  @{ Name = "DEEPGRAM_API_KEY"; Label = "Deepgram API key" },
  @{ Name = "CARTESIA_API_KEY"; Label = "Cartesia API key" },
  @{ Name = "GROQ_API_KEY"; Label = "Groq API key" },
  @{ Name = "CEREBRAS_API_KEY"; Label = "Cerebras API key" },
  @{ Name = "LITELLM_BASE_URL"; Label = "LiteLLM base URL"; Plain = $true; Default = "http://127.0.0.1:4000" },
  @{ Name = "LITELLM_API_KEY"; Label = "LiteLLM API key" },
  @{ Name = "INFISICAL_PROJECT_ID"; Label = "Infisical project ID"; Plain = $true },
  @{ Name = "INFISICAL_ENV"; Label = "Infisical env"; Plain = $true; Default = "dev" }
)

function ConvertFrom-SecureValue {
  param([Security.SecureString] $Secure)
  if (-not $Secure -or $Secure.Length -eq 0) {
    return ""
  }

  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

$lines = @(
  "# Starlight Voice local secrets",
  "# Generated by scripts/set-secrets.ps1",
  "# Do not commit this file.",
  ""
)

foreach ($key in $keys) {
  $prompt = "$($key.Label) [$($key.Name)]"
  if ($key.Default) {
    $prompt = "$prompt (default: $($key.Default))"
  }
  $prompt = "$prompt - leave blank to skip"

  if ($key.Plain) {
    $value = Read-Host $prompt
  } else {
    $value = ConvertFrom-SecureValue (Read-Host $prompt -AsSecureString)
  }

  if (-not $value -and $key.Default) {
    $value = $key.Default
  }

  if ($value) {
    $escaped = $value.Replace("`r", "").Replace("`n", "")
    $lines += "$($key.Name)=$escaped"
  }
}

Set-Content -LiteralPath $envPath -Value $lines -Encoding UTF8

Write-Host "Wrote local secrets to $envPath"
Write-Host "This file is gitignored. Do not paste its contents into chat."
